translations/ui-plugin-find-package-title/ar.json
translations/ui-plugin-find-package-title/ca.json
translations/ui-plugin-find-package-title/da.json
translations/ui-plugin-find-package-title/de.json
translations/ui-plugin-find-package-title/en_GB.json
translations/ui-plugin-find-package-title/en_SE.json
translations/ui-plugin-find-package-title/en_US.json
translations/ui-plugin-find-package-title/es.json
translations/ui-plugin-find-package-title/es_419.json
translations/ui-plugin-find-package-title/es_ES.json
translations/ui-plugin-find-package-title/fr.json
translations/ui-plugin-find-package-title/fr_FR.json
translations/ui-plugin-find-package-title/he.json
translations/ui-plugin-find-package-title/hu.json
translations/ui-plugin-find-package-title/it_IT.json
translations/ui-plugin-find-package-title/ja.json
translations/ui-plugin-find-package-title/pt_BR.json
translations/ui-plugin-find-package-title/pt_PT.json
translations/ui-plugin-find-package-title/ru.json
translations/ui-plugin-find-package-title/ur.json
translations/ui-plugin-find-package-title/zh_CN.json
translations/ui-plugin-find-package-title/zh_TW.json

Update translation strings as of 20200526T141248

---

translations/ui-plugin-find-package-title/pt_BR.json
translations/ui-plugin-find-package-title/ru.json

Update translation strings as of 20200527T144757

---

translations/ui-plugin-find-package-title/ar.json

Update translation strings as of 20200602T151309

---

.eslintrc
.gitignore
CHANGELOG.md
src/FindPackageTitlePlugin.js
src/components/CheckboxColumn/CheckboxColumn.css
src/components/CheckboxColumn/CheckboxColumn.js
src/components/CheckboxColumn/index.js
src/components/SearchModal/SearchModal.css
src/components/SearchModal/SearchModal.js
src/components/SearchResultsList/SearchResultsList.js
test/bigtest/constants/index.js
test/bigtest/constants/packages.js
test/bigtest/interactors/plugin.js
test/bigtest/network/config.js
test/bigtest/tests/find-package-test.js
translations/ui-plugin-find-package-title/en.json

* Add ability to select multiple packages in the plugin

UIPFPAT-4: Ability to multiple select packages

---

translations/ui-plugin-find-package-title/ar.json
translations/ui-plugin-find-package-title/ca.json
translations/ui-plugin-find-package-title/da.json
translations/ui-plugin-find-package-title/de.json
translations/ui-plugin-find-package-title/en_GB.json
translations/ui-plugin-find-package-title/en_SE.json
translations/ui-plugin-find-package-title/en_US.json
translations/ui-plugin-find-package-title/es.json
translations/ui-plugin-find-package-title/es_419.json
translations/ui-plugin-find-package-title/es_ES.json
translations/ui-plugin-find-package-title/fr.json
translations/ui-plugin-find-package-title/fr_FR.json
translations/ui-plugin-find-package-title/he.json
translations/ui-plugin-find-package-title/hu.json
translations/ui-plugin-find-package-title/it_IT.json
translations/ui-plugin-find-package-title/ja.json
translations/ui-plugin-find-package-title/pt_BR.json
translations/ui-plugin-find-package-title/pt_PT.json
translations/ui-plugin-find-package-title/ru.json
translations/ui-plugin-find-package-title/ur.json
translations/ui-plugin-find-package-title/zh_CN.json
translations/ui-plugin-find-package-title/zh_TW.json

Update translation strings as of 20200716T140311

---

translations/ui-plugin-find-package-title/fr_FR.json
translations/ui-plugin-find-package-title/pt_BR.json
translations/ui-plugin-find-package-title/zh_CN.json

Update translation strings as of 20200721T202356

---

CHANGELOG.md
package.json

Updated stripes to v5

---

CHANGELOG.md
package.json

Update react-intl 5.8.0

---

translations/ui-plugin-find-package-title/it_IT.json

Update translation strings as of 20201013T203429

---

CHANGELOG.md
package.json
src/components/SearchModal/SearchModal.js
src/components/SearchResultsList/SearchResultsList.js
test/bigtest/helpers/helpers.js
test/bigtest/network/config.js
test/bigtest/tests/find-package-test.js
test/bigtest/tests/find-title-test.js

Fixed incorrect number of results shown for Title search
[UIPFPAT-12](https://issues.folio.org/browse/UIPFPAT-12)

UIPFPAT-12: Title search is returning inaccurate results

---

CHANGELOG.md
src/components/SearchForm/SearchForm.js

Show Access Status Type filter
[UIPFPAT-15](https://issues.folio.org/browse/UIPFPAT-15)

UIPFPAT-15 Fix Titles: Search by Access status type does not display results

---

CHANGELOG.md
package.json

Increment stripes to v7 and react v17
[UIPFPAT-36](https://issues.folio.org/browse/UIPFPAT-36)

UIPFPAT-36: Increment stripes to v7 and react v17

---

CHANGELOG.md
src/components/SearchModal/SearchModal.js
src/components/SearchResultsList/SearchResultsList.js

* was added pagination for packages and titles

UIPFPAT-41 Apply prev/next pagination to Packages and Titles results

---

CHANGELOG.md
src/components/SearchModal/SearchModal.js

Refactor the `SearchModal` component to fix the code smell related to high Cognitive Complexity of the `fetchItems` function.
[UIPFPAT-27](https://issues.folio.org/browse/UIPFPAT-27)

UIPFPAT-27: Refactor the SearchModal component

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

Issue: update NodeJS to v16 in GitHub Actions
https://issues.folio.org/browse/UIPFPAT-44

UIPFPAT-44: update NodeJS to v16 in GitHub Actions

---

package.json

Generate coverage report for tests

Add coverage generation to test script

---

src/components/SearchModal/SearchModal.js

Enable focus on first result item for Package search
[UIPFPAT-47](https://issues.folio.org/browse/UIPFPAT-47)

UIPFPAT-47 Enable focus on first item for package search

---

CHANGELOG.md
package.json

bump stripes to 8.0.0 for Orchid/2023-R1
[UIPFPAT-52](https://issues.folio.org/browse/UIPFPAT-52)

UIPFAT-52 bump stripes to 8.0.0 for Orchid/2023-R1

---

CHANGELOG.md
package.json

migrate stripes deps and react-intl to sunflower
[UIPFPAT-64](https://folio-org.atlassian.net/browse/UIPFPAT-64)
[UIPFPAT-65](https://folio-org.atlassian.net/browse/UIPFPAT-65)

migrate stripes deps and react-intl to sunflower

---

CHANGELOG.md
src/components/CheckboxColumn/CheckboxColumn.js

React v19: refactor away from default props for functional components.
[UIPFPAT-60](https://folio-org.atlassian.net/browse/UIPFPAT-60)

UIPFPAT-60 React v19: refactor away from default props for functional components.
